### ISSUE TITLE
Does not work with socket.io version 3/4

### ISSUE THREAD

**Issue by N00nDay** [mother/socket.io-adapter-mongo#10]
Does not work with socket.io version 3/4. Is there any road map for updating this to work with version 3/4?

**Comment by N00nDay** [comment]
After digging into this. All that needs to be done is update socket.io-adapter package and all works great. Whoever the maintainer is just needs to do that and all will work.

**Comment by asabhaney** [comment]
Made some fixes in this PR: https://github.com/mother/socket.io-adapter-mongo/pull/13. It doesn't address socket.io v3/4 compatibility, but this library is essentially unmaintained except for patches. Happy to accept PRs or transfer to a new maintainer though.
