### ISSUE TITLE
Status of Maintenance, Update Needed -- current URL string parser is depricated

### ISSUE THREAD

**Issue by ThreeDfish** [mother/socket.io-adapter-mongo#3]
I am getting this warning message when I connect with this:

(node:84416) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

Looking at the dependencies, I see that there are new versions for several of the dependencies.  Most likely this problem could be solved by updating the dependencies.

Is this package still being maintained?   If I were to fix the issue and issue a PR, would it be pulled into the code?

Please let me know.

**Comment by asabhaney** [comment]
Would be happy to accept a PR, thanks!

**Comment by ThreeDfish** [comment]
Ok, I created a PR to fix the issue.

**Comment by asabhaney** [comment]
Closed via #4
